# pubspec.yaml

name: t_posture_gym
description: "App para una Buena Postura"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0' # Asegúrate que coincida con tu SDK

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # --- NUESTRAS DEPENDENCIAS ---
  go_router: ^14.2.0     # Para el manejo de rutas (navegación)
  google_fonts: ^6.2.1   # Para cargar fácilmente 'Space Grotesk'
  phosphor_flutter: ^2.1.0  # Para los iconos de Phosphor

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- AÑADE TUS ASSETS (IMÁGENES) ---
  assets:
    - assets/images/ # Declara la carpeta
    - assets/images/FondoLog.jpg

  # --- AÑADE TUS FUENTES ---
  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        # (Añade más pesos si los tienes, ej. Light, Medium)